### ISSUE TITLE
Cannot activate integration.

### ISSUE THREAD

**Issue by spogulis** [mageplaza/magento-2-social-share#3]
Hello,

The Social Share module requires integration activation but when clicking "Activate", the activation is not happening due to redirection to a parked domain.

![image](https://user-images.githubusercontent.com/37654814/71254446-a498c100-2333-11ea-98df-2be93e7af652.png)
![image](https://user-images.githubusercontent.com/37654814/71254470-b4180a00-2333-11ea-932d-05b0905c7ac5.png)
![image](https://user-images.githubusercontent.com/37654814/71254482-c003cc00-2333-11ea-90bf-572a9067c16b.png)

How to activate the module?

**Comment by Desmond-Mageplaza** [comment]
Hi,

Maybe you have misunderstood the activation feature of the module with the integration activation.
Those 2 features are completely different.

If you have any problem when activating the Social Share module, you can take a look at this issue:
https://github.com/mageplaza/module-core/issues/26
Hope this might help you somehow.

**Comment by Desmond-Mageplaza** [comment]
It's been 7 days without any further response so I will close this issue.
Thank you for your interest in the extension.
