### ISSUE TITLE
Its not working with the production mode

### ISSUE THREAD

**Issue by jigar48** [mageplaza/magento-2-social-share#5]
getting this error on product page when production mode is enabled. 

Magento version is 2.3.2

![mageplaza_socialshare_console_error](https://user-images.githubusercontent.com/16815711/79422422-7a51ca00-7fda-11ea-8b73-e4800878c356.png)

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your question.
Please try to un-min and un-merge JS and deploy your site again.
Then try again and let me know about the result.
Thank you!

**Comment by Victor-Mageplaza** [comment]
I will close this issue here due to no response after 7 days
Many thanks!
