### ISSUE TITLE
Not working with js minification ON.

### ISSUE THREAD

**Issue by rizwankhaan** [mageplaza/magento-2-social-share#6]
The module is not working as js is missing https://static.addtoany.com/menu/page.min.js due to minification.

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your question.
Can you try the developed version and l let me know the result?
Thank you!

**Comment by rizwankhaan** [comment]
HI @Victor-Mageplaza 
I have resolved this issue by excluding that JS from minification and it is working fine now.
we can close this issue.
Thanks

**Comment by Victor-Mageplaza** [comment]
Yes, that is also a reasonable solution.
However, I did update the bug in brach develop so if you want to try, please download the develop version.
Thank you!
